---
title: "STAT 302"
description: |
  Statistical Software and its Applications
site: distill::distill_website
output:
  distill::distill_article:
    self_contained: false
---

Materials for this course were originally developed by [Bryan Martin](https://bryandmartin.github.io/STAT302/index.html).

# Schedule 

### Week One 

* **M 06/20**: No class - Juneteenth
* **W 06/22**: Short lab 0 assigned

### Week Two

* **M 06/27**: Short lab 0 due before class; Short Lab 1 assigned 
* **W 06/29**: Short lab 1 due before class; Lab 1 assigned

### Week Three

* **M 07/04**: No class - July 4th
* **W 07/06**: Lab 2 assigned

### Week Four

* **M 07/11**: Lab 1 due before class
* **W 07/13**: Lab 2 due before class, Project 1 assigned

### Week Five

* **M 07/18**: No new assignment
* **W 07/20**: (optional/extra credit) Short lab 2 assigned

### Week Six

* **M 07/25**: Project 1 and (optional/extra credit) Short lab 2 due at 11:59 PM; Short lab 3 assigned
* **W 07/27**: Short lab 3 due before class; Lab 3 assigned

### Week Seven

* **M 08/01**: No new assignment
* **W 08/03**: Lab 3 due before class; Project 2 assigned

### Week Eight

* **M 08/08**: No new assignment
* **W 08/10**: Short lab 4 assigned

### Week Nine

* **M 08/15**: Project 2 due by 11:59 PM; Short lab 5 assigned
* **W 08/17**: Short lab 4 and Short lab 5 due before class; Lab 4 assigned

### Week Ten

* **M 05/30**: No new assignment
* **W 06/01**: Lab 4 due before class; Project 3 assigned

### Finals Week 
* **M 08/19**: Project 3 due at 11:59 PM



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

# Learn more about publishing to GitHub Pages at:
# https://rstudio.github.io/distill/publish_website.html#github-pages

```

